version: 0.2


env:
  variables:
    S3_BUCKET_NAME: "urlshort-cloudfront-website"
    CLOUDFRONT_DISTRIBUTION_ID: "E135O407T9WZ07"

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      # Try to get changed files using git, fallback to all .js files if not a git repo
      - export CHANGED_LAMBDAS=$(ls src/*.js | xargs -n1 basename | sed 's/\.js$//')
      - echo "Changed Lambdas -> $CHANGED_LAMBDAS"
  build:
    commands:
      - |
        echo "$CHANGED_LAMBDAS" | while read -r lambda; do
          echo "Packaging and deploying $lambda"
          cd src
          zip ../${lambda}.zip ${lambda}.js
          cd ..
          aws lambda update-function-code --function-name $lambda --zip-file fileb://${lambda}.zip --region $AWS_REGION
        done
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '*.zip'
